# disable aws parameterstore
spring.cloud.aws.parameterstore.enabled=false
# actuator
management.endpoint.health.show-details=always
# JPA defaults
spring.sql.init.mode=always
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
